// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBDcUqhskNBkEpWLAMMfx5tgBlwO_BiGc',
    appId: '1:399742630456:web:b53c386f0b54abecf6c4cd',
    messagingSenderId: '399742630456',
    projectId: 'growgarden-final',
    authDomain: 'growgarden-final.firebaseapp.com',
    databaseURL: 'https://growgarden-final-default-rtdb.firebaseio.com',
    storageBucket: 'growgarden-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5EUZSZRkUw5TxxmZdUrcN2yqlcbevKD8',
    appId: '1:399742630456:android:bf899490a7e1bf83f6c4cd',
    messagingSenderId: '399742630456',
    projectId: 'growgarden-final',
    databaseURL: 'https://growgarden-final-default-rtdb.firebaseio.com',
    storageBucket: 'growgarden-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnkFY_l6Ico4Sdm-BSsB4HMtZ4aqUGHE4',
    appId: '1:399742630456:ios:942ad544f50bca5ef6c4cd',
    messagingSenderId: '399742630456',
    projectId: 'growgarden-final',
    databaseURL: 'https://growgarden-final-default-rtdb.firebaseio.com',
    storageBucket: 'growgarden-final.appspot.com',
    iosClientId:
        '399742630456-f37nsdjrq60jfhdln7goonhfrk85f1i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.growgardenRtd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnkFY_l6Ico4Sdm-BSsB4HMtZ4aqUGHE4',
    appId: '1:399742630456:ios:942ad544f50bca5ef6c4cd',
    messagingSenderId: '399742630456',
    projectId: 'growgarden-final',
    databaseURL: 'https://growgarden-final-default-rtdb.firebaseio.com',
    storageBucket: 'growgarden-final.appspot.com',
    iosClientId:
        '399742630456-f37nsdjrq60jfhdln7goonhfrk85f1i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.growgardenRtd',
  );
}
